### ISSUE TITLE
Accounts inserted missing AccLevel

### ISSUE THREAD

**Issue by MikeJeffers** [OpenPerpetuum/perpetuum-api#2]
https://github.com/OpenPerpetuum/perpetuum-api/blob/master/module/Onboarding/src/Controller/ConsoleController.php#L175
Needs account level set (DB default is 16777216 - invalid)

Should be set to 2 explicitly

https://github.com/OpenPerpetuum/perpetuum-api/blob/master/module/Onboarding/src/V1/Rpc/Register/RegisterController.php#L21
here?

**Comment by bartbrinkman** [comment]
This is the ORM mapping for Account (accounts table):

https://github.com/OpenPerpetuum/perpetuum-api/blob/master/module/Onboarding/src/Entity/Account.php

It never had mapping for account level, so this shouldn't be an API issue. At least now a new one.

**Comment by MikeJeffers** [comment]
This is a global issue for any account inserted from api; updating issue

**Comment by bartbrinkman** [comment]
Permanent fix with this commit:

https://github.com/OpenPerpetuum/perpetuum-api/commit/80911f485a8e26ebbc55f79f6a9d774fe5779935
