### ISSUE TITLE
Resend Verification Fails on some? accounts

### ISSUE THREAD

**Issue by MikeJeffers** [OpenPerpetuum/perpetuum-api#3]
Resend fails to send verification showing: "We couldn't find your account with that email."

Tested with 33mail alias, successfully received the _initial_ verification email, did not click on it, and clicked resend to test.
Error was displayed as quoted.

**Comment by bartbrinkman** [comment]
Should be fixed. When resending the mail, the API now checks only for the site account, which is created on both scenarios (site and game). When creating an account on the site, the server account is created only after verification.
